version: '3.9'

services:
  app:
    container_name: consure-app
    build: .
    ports:
    - "8123:8123"
    restart: on-failure
    volumes:
    - api:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - consure

  mysql:
    image: mysql:latest
    container_name: consure-mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$DB_PASSWORD"]
      interval: 60s
      retries: 15
      start_period: 30s
    volumes:
      - db:/var/lib/mysql
    networks:
      - consure
  
  adminer:
    image: adminer
    container_name: consure-adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - consure

volumes:
  api:
  db:

networks:
  consure:
    driver: bridge